### ISSUE TITLE
intaker

### ISSUE THREAD

**Issue by muffinslapperjr** [unlv-asme-sdc/ASME-UNLV-RoboLib#12]
unsure of intaker's correctness, also unimplemented in final skeleton code. Should be ready. Hopefully. Making this an issue for status update.

**Comment by HumanUnahm** [comment]
Cleaned up the code a bit and fix some syntax errors, https://github.com/unlv-asme-sdc/ASME-UNLV-RoboLib/commit/b568252371d2bd9a54e6d30d58175c22c0cf8dcc.
