### ISSUE TITLE
controller deadzone

### ISSUE THREAD

**Issue by muffinslapperjr** [unlv-asme-sdc/ASME-UNLV-RoboLib#3]
Driving tank drive and trying to go slow showcases that the right side is more sensitive than the left side. decrease left's to normalize.

**Comment by HumanUnahm** [comment]
Was actually a bug with Arduino's abs(). Resolved with commit https://github.com/unlv-asme-sdc/ASME-UNLV-RoboLib/commit/43871b9d85be37904a9b2d519cd8c25e79f81aeb.
